### ISSUE TITLE
Rename this repository (its name won't explain its content soon)

### ISSUE THREAD

**Issue by jesusgn90** [islos-efe-eme/gta-tools#32]
Our repository is growing, and is going to grow day by day. Issues like https://github.com/islos-efe-eme/auto-news/issues/31 made me feel like the name of the repository won't be valid soon.

**Feb 11@20:00 this repository will be renamed @islos-efe-eme/gta-team**

Please put your suggestions as a single or multiple comments before the end hour.

**Comment by jesusgn90** [comment]
My suggestions: 

- islos-tools
- gta-tools

**Comment by crolopez** [comment]
I wouldn't use the word 'islos' as only a few taco-speakers relate it to GTA. My proposals:

- gta-experience
- gta-utils
- gta4u

**Comment by jesusgn90** [comment]
Finally, `gta-tools` is the winner
