### ISSUE TITLE
Do not repeat the first steps in each README.md

### ISSUE THREAD

**Issue by crolopez** [islos-efe-eme/gta-tools#39]
Hi team,

We are currently repeating more than the half part of the readme file for each module. I think the first steps (requirements and how to build) could be centralized in the project root readme.

- [Slack](https://github.com/islos-efe-eme/gta-tools/blob/v1.0.1/slack/README.md)
- [Telegram](https://github.com/islos-efe-eme/gta-tools/blob/v1.0.1/telegram/README.md)
- [Parser](https://github.com/islos-efe-eme/gta-tools/blob/v1.0.1/parser/README.md)
- [DB (future feature)](https://github.com/islos-efe-eme/gta-tools/blob/9d011f0bbf9354126ea6fb2108cdaacce5213a26/db/README.md)

**Comment by jesusgn90** [comment]
I agree with this one, but don't you think this is mostly covered in https://github.com/islos-efe-eme/gta-tools/issues/16 ? If so, close this, otherwise please add more context about why this should be opened, thx!
